### ISSUE TITLE
python3 compatibility for nimfa?

### ISSUE THREAD

**Issue by nadesai** [marinkaz/MF#15]
I've been using nimfa's NMF implementation for a bit, but recently switched to a python3 environment and decided to install it there. When I attempt to import nimfa in python3.4, I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/nimfa/__init__.py", line 18, in <module>
    from mf_run import *
ImportError: No module named 'mf_run'
```
It seems this is because python3 requires [explicit relative imports](http://stackoverflow.com/questions/12172791/changes-in-import-statement-python3), so the correct import statement would be `from .mf_run import *`. After some more digging, I found several places where the library is not currently python3 compatible. I ran the `2to3` utility on the library in order to look for more, and got a number of changes that I have recorded in the following diff: https://gist.github.com/nadesai/0727db6af37383a153e9.

Are there any long-term plans to address these compatibility issues, and perhaps allow the library to be used under python3?

**Comment by marinkaz** [comment]
Thanks, Nimfa should now be python3 compatible.
