### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by Neiberg** [marinkaz/MF#16]
I have tried both 1.1 and master (as of 2015-03-19) using Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32 and both produce "TypeError: super() takes at least 1 argument (0 given)" when running:

import nimfa
V = nimfa.examples.medulloblastoma.read(normalize=True)
lsnmf = nimfa.Lsnmf(V, seed='random_vcol', rank=50, max_iter=100)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nimfa\methods\factorization\lsnmf.py", line 145, in __init__
    super().__init__(vars())
TypeError: super() takes at least 1 argument (0 given)

**Comment by marinkaz** [comment]
Fixed.
